<?php

use Hyva\Theme\Model\ViewModelRegistry;
use InPost\InPostPay\ViewModel\Widget;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Widget $widgetViewModel */
/** @var Escaper $escaper */

$widgetViewModel = $viewModels->require(Widget::class);

$widgetViewModel = $block->getData('widget_view_model');
if (!$widgetViewModel->isEnabled() || !$widgetViewModel->isEnabledOnCheckoutPage()) {
    return;
}

$bindingPlace = $block->getBindingPlace();
$layoutConfig = $widgetViewModel->getLayoutConfig();
$widgetWrapperClass = "inpay-widget-wrapper";
?>

<div x-data="initializeInpostPayCheckout"
     x-on:private-content-loaded.window="receiveCustomerData"
     class="<?= $escaper->escapeHtmlAttr($widgetWrapperClass) . ' ' . $escaper->escapeHtmlAttr($bindingPlace) ?>">
    <inpost-izi-button
        binding_place="<?= $escaper->escapeHtmlAttr($bindingPlace) ?>"
        variation="<?= $escaper->escapeHtmlAttr($layoutConfig) ?>"
    ></inpost-izi-button>
</div>

